# 全局配置
server:
  # 端口
  port: 9001
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
spring:
  resources:
    #静态资源地址
    static-locations: classpath:/static/,classpath:/static/upload/
    # orm框架配置
  jpa:
    show-sql: true
    open-in-view: true
    #数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/papers_recheck?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    #配置请求连接
  elasticsearch:
    rest:
      uris: 47.105.156.64:9200
  #配置对象连接
elasticsearch:
  ip: 47.105.156.64:9200